name: Release
description: Create a release
author: Me

inputs:
  version:
    description: Version
    required: true
  token:
    description: Token
    required: true

runs:
  using: node20
  main: index.js
