name: Upload
description: Upload a release asset
author: Me

inputs:
  release:
    description: Release
    required: true
  path:
    description: Path
    required: true
  token:
    description: Token
    required: true

runs:
  using: node20
  main: index.js
