name: CI

on:
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: echo "hello" >> file.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
