name: Auto Commit

on:
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $(date +%Y-%m-%d) >> file.txt
          git add --all
          git commit -m "test commit"
          git push
