name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install @actions/core @actions/github
      - uses: ./.github/actions/release
        id: release
        with:
          version: ${{ github.ref }}
          token: ${{ secrets.MY_TOKEN }}
      - run: echo ${{ steps.release.outputs.id }}
      - run: echo ${{ steps.release.outputs.upload_url }}
