name: Out of this World

on:
  push:
    tags:
      - "v*"

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - run: npm install @actions/core @actions/github
      - uses: ./.github/actions/release
        with:
          version: ${{ github.ref }}
